// Generated by tools/build-builds.mjs — do not edit by hand
window.VS_BUILDS = [
  {
    "schema": 1,
    "id": "bloody-tear-crit-solo",
    "name": "Bloody Tear Crit Solo",
    "author": "misterwtheface",
    "description": "Whip -> Bloody Tear crit opener with a Clock Tower absorb-union.",
    "tags": [
      "solo",
      "crit",
      "whip"
    ],
    "dataVersion": "2026-08",
    "playerCount": 1,
    "stage": "Mad Forest",
    "arcana": [
      "Gemini (I)",
      "Sarabande of Healing (VI)",
      null
    ],
    "players": [
      {
        "character": "Antonio Belpaese",
        "charLevel": 1,
        "weapons": [
          "Bloody Tear",
          "King Bible",
          "Fire Wand",
          "Clock Tower"
        ],
        "passives": [
          "Hollow Heart",
          "Spinach",
          "Duplicator"
        ],
        "extraPassives": [],
        "giftWeapon": null,
        "giftPassive": null,
        "familiars": [],
        "absorbed": {
          "Clock Tower": [
            "Endo Gears",
            "Peri Pendulum",
            "Myo Lift",
            "Epi Head"
          ]
        }
      }
    ]
  }
];
