/**
 * build-builds.mjs
 * Bundles every builds/*.json into builds/builds.js, which sets window.VS_BUILDS.
 * The site loads that bundle via a <script> tag (no fetch), so featured builds work
 * on file:// and GitHub Pages alike — mirroring how data/data.js is loaded.
 *
 * Usage: node tools/build-builds.mjs   (from vs-build-calc root)
 *
 * See builds/SCHEMA.md for the build JSON contract.
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';
import vm from 'vm';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT  = join(__dirname, '..');
const BUILDS_DIR = join(REPO_ROOT, 'builds');
const OUT_FILE   = join(BUILDS_DIR, 'builds.js');

// Load game data (data/data.js sets window.VS_DATA) + the shared legality validator so repo
// builds are held to the SAME rules the site enforces on import. Both are plain browser files;
// load them through a tiny window shim.
const require = createRequire(import.meta.url);
let VS_DATA = null, validateBuild = null;
try {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(readFileSync(join(REPO_ROOT, 'data', 'data.js'), 'utf8'), sandbox);
  VS_DATA = sandbox.window.VS_DATA;
  ({ validateBuild } = require(join(BUILDS_DIR, 'validate.js')));
} catch (e) {
  console.warn(`  ⚠ legality validation unavailable (${e.message}) — bundling without it`);
}

// Files that live in builds/ but are not builds.
const SKIP = new Set(['builds.js', 'index.json']);

const REQUIRED = ['id', 'name', 'playerCount', 'players'];

function loadBuild(file) {
  const path = join(BUILDS_DIR, file);
  let obj;
  try {
    obj = JSON.parse(readFileSync(path, 'utf8'));
  } catch (e) {
    console.warn(`  ⚠ ${file}: invalid JSON — skipped (${e.message})`);
    return null;
  }
  if (obj.schema !== 1) {
    console.warn(`  ⚠ ${file}: missing/unknown "schema" (expected 1) — skipped`);
    return null;
  }
  const missing = REQUIRED.filter(k => obj[k] === undefined || obj[k] === null);
  if (missing.length) {
    console.warn(`  ⚠ ${file}: missing required field(s): ${missing.join(', ')} — skipped`);
    return null;
  }
  if (!Array.isArray(obj.players) || obj.players.length === 0) {
    console.warn(`  ⚠ ${file}: "players" must be a non-empty array — skipped`);
    return null;
  }
  // id defaults to the filename stem if the author left it blank/mismatched.
  if (!obj.id) obj.id = file.replace(/\.json$/i, '');
  return obj;
}

const files = readdirSync(BUILDS_DIR)
  .filter(f => f.toLowerCase().endsWith('.json') && !SKIP.has(f))
  .sort();

const builds = [];
const seen = new Set();
for (const file of files) {
  const b = loadBuild(file);
  if (!b) continue;
  if (seen.has(b.id)) { console.warn(`  ⚠ ${file}: duplicate id "${b.id}" — skipped`); continue; }
  // Legality check — an illegal build (bad requirements, wrong-stage Academy Badge, dupes, …)
  // is dropped from the bundle so the live site never serves an unachievable loadout.
  if (validateBuild && VS_DATA) {
    const { errors, warnings } = validateBuild(b, VS_DATA);
    warnings.forEach(w => console.warn(`  ⚠ ${file}: ${w}`));
    if (errors.length) { errors.forEach(er => console.error(`  ✗ ${file}: ${er}`)); console.error(`  ✗ ${file}: ILLEGAL build — excluded from bundle`); continue; }
  }
  seen.add(b.id);
  builds.push(b);
}

const banner = '// Generated by tools/build-builds.mjs — do not edit by hand\n';
writeFileSync(OUT_FILE, banner + 'window.VS_BUILDS = ' + JSON.stringify(builds, null, 2) + ';\n');

console.log(`Bundled ${builds.length} build(s) from ${files.length} file(s) → builds/builds.js`);
